Repository massalabs/ui-kit, pull requests merged in 2023-05, with the labels that each got.

#31 fix font Urban filename
  src/global.css
Labels: bug

#41 Added SvgIcon component
  src/assets/svg-components/MassaLogo.tsx
  src/assets/svg-components/MassaToken.tsx
  src/components/Icons/Svg/SvgIcon.stories.tsx
  src/components/Icons/Svg/SvgIcon.test.tsx
  src/components/Icons/Svg/index.ts
  src/components/Password/Password.test.tsx
Labels: P1

#46 add `<Input>` component
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.test.tsx
  src/components/Input/Input.tsx
  src/components/Input/index.ts
Labels: P2

#45 update password to apply global style
  src/components/Password/Password.stories.tsx
  src/components/Password/Password.tsx
Labels: P2

#53 add selector
  src/components/AccountSelector/AccountSelectButton/AccountSelector.stories.tsx
  src/components/AccountSelector/AccountSelectButton/AccountSelector.test.tsx
  src/components/AccountSelector/AccountSelectButton/AccountSelectorButton.tsx
  src/components/AccountSelector/AccountSelectButton/index.ts
  src/components/AccountSelector/index.ts
  src/components/index.ts
Labels: P1

#35 added colors
  package-lock.json
  presets/massa-station-preset.js
  src/components/Colors/Color/Color.tsx
  src/components/Colors/Color/index.ts
  src/components/Colors/Colors.stories.tsx
  src/components/Colors/Colors.tsx
Labels: P3

#71 add tabs component
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/index.ts
  src/components/index.ts
  src/global.css
Labels: Frontend

#90 wails: add missing export for components
  src/components/index.ts
Labels: Frontend
